version: "3"

services:
  backend:
    container_name: swd.backend.dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: /bin/sh -c "yarn; yarn run prisma migrate dev; yarn prisma:gen; yarn start:dev"
    ports:
      - "8080:8080"
    volumes:
      - node_modules:/app/node_modules
      - ./:/app:z
    environment:
      - DATABASE_URL
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_IS_SECURE
      - SMTP_AUTH_USERNAME
      - SMTP_AUTH_PASSWORD
      - SMTP_TEMPLATES_DIR
      - SMTP_DEFAULT_SENDER
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    container_name: swd.postgresql.dev
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: swd.mailhog.dev
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  dbdata:
  node_modules: